site_name: RL-PLG
site_description: >
  Technical documentation for rlplg, a python library.

nav:
  - RL-PLG Home: 'index.md'
  - Development: 'dev.md'
  - Environments:
    - ABCseq: 'envs/abcseq.md'
    - GridWorld: 'envs/gridworld.md'
    - RedGreen: 'envs/redgreen.md'
    - StateRandomWalk: 'envs/staterandomwalk.md'
    - IceWorld: 'envs/iceworld.md'
    - TowerOfHanoi: 'envs/towerofhanoi.md'
    - Template: 'envs/template.md'
